#! /bin/bash
# you can skip LDFLAGS=-lrt when using libressl 2.0.1
touch /usr/src/boringssl/Makefile

echo "clean:" > /usr/src/boringssl/Makefile
echo "" >> /usr/src/boringssl/Makefile
echo "all:" > /usr/src/boringssl/Makefile
echo "" >> /usr/src/boringssl/Makefile
echo "install:" > /usr/src/boringssl/Makefile
echo "" >> /usr/src/boringssl/Makefile